INSERT IGNORE INTO catalogo_otros (descripcion) VALUES
('Electrobisturí'),
('Canula de aspiración'),
('Material de Neo'),
--('Coviden Dra Coila'),
--('Mat Dra Ruiz'),
('Cortaclavija'),
('Corrugados'),
('Aspiración fina'),
('Aspiración doble vía'),
('Venda Smarch'),
--('Mat uti'),
('Pinza Diente Perro'),
('Pinza (Electricidad)'),
('Aguja'),
('Sutura'),
--('Punch Dra Lacerda'),
('Manguita'),
('Mango de Cialítica'),
('Sonda'),
('Equipo descartable'),
('Pinza de Trauma'),
('Pinza Coviden Liga Sure'),
('Aspiración de Silicona'),
('Gamusa de neuro'),
('Motor'),
('Impermeables'),
('Cajas de cateters'),
('Bandeja de cx'),
('I.A'),
('Mano de foco'),
('Pirex'),
('Bandeja blanca'),
('Precicup'),
('Tapones azules'),
('Caja chalazion'),
('Plastico chico'),
('Plastico grande'),
('Fibra'),
('Bandeja de cirugía'),
('Pinza de campo'),
('Inyector alcon'),
('Chop'),
('Tapón de Silicona'),
('Bata'),
('Toalla chica'),
('Campo de tela chico'),
('Campo de tela grande'),
('Campo chalazión'),
('Vitectromo'),
('Tijera'),
('Caja refractiva'),
('Caja cross'),
('Bandeja blanca'),
('Caja de Lucentis'),
('Tupper refractivo'),
('Filtro'),
('Sonda Foley'),
('Moria'),
('Diazemia'),
('Caja Puntum Piug'),
('Cepillo'),
('Fresita'),
('Moscones nebulizadores'),
('Moscones nebulizadores pediátricos'),
('K-33'),
('K-32'),
('K-31'),
('K-9');